# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeIMOKftPiVYH7n9K8LmMfMUN_tindwx
"""

a=int (input())
if a==1:
  print ("Январь")
elif a==2:
    print ("Февраль")
elif a==3:
    print ("Март")
elif a==4:
    print ('Апрель')
elif a==5:
    print ('Май')
elif a==6:
    print ('Июнь')
elif a==7:
    print ('Июль')
elif a==8:
    print ('Август')
elif a==9:
    print ('Сентябрь')
elif a==10:
    print ('Октябрь')
elif a==11:
    print ('Ноябрь')
elif a==12:
    print ('Декабрь')
else:
  print ("Нет такого месяца")

a=int(input())
if a % 2 !=0:
  print ("Нечетное")
else:
  print ("Четное")

n=int(input())
if n>40:
  print ("Stonks")
elif n<40:
  print ("not stonks")
else:
  print ("Мне нечего сказать вам")

def is_year_leap (n):
  if n % 4 == 0:
  if n % 100 == 0:
  if n % 400 ==0:
    print ("True")
  else:
    print ("False")
a=int(input())
print(is_year_leap(a))

def is_prime (n):